### ISSUE TITLE
Could make abstract and objectives fill both columns. DISCUSS

### ISSUE THREAD

**Issue by rsmith013** [cedadev/datamad2#101]
Not sure. It might look more sensible as the text is really long.

e.g. https://datamad-test.ceda.ac.uk/grant/1684/

**Comment by rsmith013** [comment]
Put <th>Abstract</th> in it's own <tr> and make a new row for the content. Use colspan=2 to make it span across the two rows.

**Comment by ellesmith88** [comment]
Possibly add paragraphs in as well.
