### ISSUE TITLE
Filtering on all fields?

### ISSUE THREAD

**Issue by ellesmith88** [cedadev/datamad2#120]
Discussed to solve issues of different data centres looking at different things

**Comment by ellesmith88** [comment]
Looking at the current fields available and previous feedback I have collated a list of fields it would be useful to filter by and search by (in the search bar):

Filter by:
Date created (by a range)
Grant status
Data centre
Routing classification
Secondary classification
Main science area OR any science area mentioned (?)
Proposed start/end date (by a range)
Actual start/end date (by a range)
Amount awarded (by a range)
Grant type
Scheme
Call
Facility
Lead grant
NCAS
NCEO
Claim status
Grade (overall score) (by range) - once added

Search by:
Grant reference
Title
PI (Grant holder) 
Claim status
Data centre
Other data centre
Routing classification
Science area(?)
Department
Research org
Parent grant - i.e. searching for a grant ref brings up those grants for which it is parent grant as well?

**Comment by rsmith013** [comment]
Nice, thanks.
I did wonder whether we should add a "filter subscription" capability. I.e. Allow the users to save which fields they want to be able to filter on. These will be open when the page loads and other filters can be presented by clicking a show_more button. 

The idea would be to reduce the amount of clutter on the screen if the filters were not useful to you. Perhaps this is an iteration once all the filters and search fields are added.

**Comment by ellesmith88** [comment]
That sounds like a good idea to me, since most users seem to have their favourite fields. Agreed that it should be an iteration though since it works well without it.
