### ISSUE TITLE
Have a way to bulk upload documents to document store

### ISSUE THREAD

**Issue by ellesmith88** [cedadev/datamad2#127]

**Comment by rsmith013** [comment]
Information from Jaana describing the current document naming convention.

> Currently the support document naming convention in the document library where NERC upload the documents is of type
> 
><Grant ref>_<DocType> with document type including CFS for case for support, DMP for outline data management plan, TA for technical appraisal, JOR for justification of resources, PROFORMA for grant proposal (not often available to us). The key types for data centres are the CFS and DMP.
> 
>The standard file name as we have in the document library now is of type
> 
>NE_T000619_1 DMP.pdf
> 
>Although they have not been fully consistent when naming documents so we also have some files of type
> 
>NE-T003510-1-DMP.pdf
> 
>Not sure if that answers your question? Happy to clarify if needed.
> 
>Jaana

I propose we standardise on <grant_ref(underscore separated)> <document_type> and reject incorrectly formatted filenames with some kind of report to remove ambiguity.

**Comment by ellesmith88** [comment]
Bulk upload works following these conventions - need to log when the file name isn't formatted correctly/ when it already exists in a report

**Comment by rsmith013** [comment]
this has been implemented
