### ISSUE TITLE
Auto create sub tasks in JIRA when making new ticket

### ISSUE THREAD

**Issue by rsmith013** [cedadev/datamad2#175]
Kate needs to give us a list. 
Could be datacentre specific so attach list to datacentre model.

**Comment by katewinfield** [comment]
This is the list. If we can schedule the top 4 then that would be amazing.

Send Initial email – schedule for 1 month after start date
Create DMP – Schedule for 3 months after start date
Check progress with PI – Schedule for 1 year after start date
Project nearing end date check progress – Schedule 6 months before end date
Archive data
Create dataset records 
Check permissions
