### ISSUE TITLE
Check how JIRA issues are linked to grants. 

### ISSUE THREAD

**Issue by rsmith013** [cedadev/datamad2#260]
How to bulk upload existing tickets. e.g. EIDC (ceh) have been using JIRA already and so have tickets. I think, if these issues have a grant ref field already, it will link to these instead of creating a new one.

**Comment by ellesmith88** [comment]
In `create_issue.py` we search for jira issues using `results = jira.search_issues(f'summary~{grant_ref}')` and then return `results[0]` if results are found.

So if the tickets have the `grant_ref` in the summary i.e. the title then they will be found.
