### ISSUE TITLE
Child grants getting listed multiple times for parent grants

### ISSUE THREAD

**Issue by rsmith013** [cedadev/datamad2#322]
**Describe the bug**
Example: `NE/R018006/1`

**To Reproduce**

**Expected behavior**
Child grants should only be listed once

**Screenshots**
![image](https://user-images.githubusercontent.com/22395703/99420532-379bfb80-28f5-11eb-97c4-dfb6150bdaf3.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Possibly related to the daily update?

**Comment by ellesmith88** [comment]
Pretty sure this is related to the daily update as the number of child grants has increased on this grant since this issue was made.
