### ISSUE TITLE
Hide/ filter unfunded grants

### ISSUE THREAD

**Issue by ellesmith88** [cedadev/datamad2#356]
Not all grants should be assigned to data centres you could be hidden so this list of 'unfunded' grants could be hidden/ filtered out in datamad

**Comment by rsmith013** [comment]
Original Message:

> We are reviewing the grant types and calls which data centres are contracted to manage data for. This came about after I looked at many of the grants in the unassigned grants view and realised they came from a limited number of grant types, which I thought we don’t currently need to contact unless they approach us to agree on data management outside our unified funding model.
>  
> What this means is that once we have updated the list of grant types that we should assign to data centres, we are then left with another list which we could (should even) hide in DataMAD2. So if possible at that point, we could set up a filter to only show unassigned ‘funded’ grants that fulfil certain conditions as a default, and to get to the ‘unfunded’ grant you need to search for them specifically. You could still create a Jira ticket for those but they would be exceptions.
>  
> Does that make sense, and do you think it is possible? We had discussed the possibility of hiding ‘closed’ grants but as that is not a hard rule, and the funded/unfunded is, it would be better to link the visibility to the funding model.

**Comment by rsmith013** [comment]
Need a rule for what constitutes a 'funded' grant before we can do this

**Comment by rsmith013** [comment]
linked to #232

**Comment by rsmith013** [comment]
Unfunded grants have Grant Type:
- NERC Strategic Capital Grants
- Public Engagement Grants
- Strategy & Partnerships (KE)

Also need a way to override this default visibility status and change it from the main view
