### ISSUE TITLE
Left on white screen after hide/unhide

### ISSUE THREAD

**Issue by ellesmith88** [cedadev/datamad2#378]
**Describe the bug**
When using the hide/ unhide feature (eye icon next to individual grants) the user is left on a white screen and not returned.

**To Reproduce**
Click on eye icon next to a grant 

**Expected behavior**
Returned to grant list

**Screenshots**
Visible at this link:
https://datamad.ceda.ac.uk/grant/1012/visibility/hide

**Comment by rsmith013** [comment]
This should be using javascript to toggle the link. thought i'd written it but seems to have got lost somewhere.
