### ISSUE TITLE
Side bar on home page disappears if you make the window size smaller

### ISSUE THREAD

**Issue by rsmith013** [cedadev/datamad2#67]

**Comment by ellesmith88** [comment]
This was meant to happen because it looked messy when the sidebar moved to the top. The filtering can still be accessed by the navigation bar drop down menu. Do you think it would be better with the sidebar back in?

**Comment by rsmith013** [comment]
It isn't very intuitive. The confusion is added to because the Title of the filters remains so it just looks like the filters have disappeared.

Perhaps you could copy catalogue.ceda which has the same concept.
The sidebar hides and a button to `show filters` appears. This does put the filters at the top but they are only visible if you want them so less of a problem visually.

https://catalogue.ceda.ac.uk/?q=&sort_by=relevance&results_per_page=20
