### ISSUE TITLE
Grant detail slow to load when it has a JIRA ticket 

### ISSUE THREAD

**Issue by ellesmith88** [cedadev/datamad2#72]
To do with getting the link for the ticket?

**Comment by rsmith013** [comment]
Do you cache the link, ie save it in the database when it is created? My quick look through the code looks like it's searching JIRA everytime. That would probably be slow and likely to get slower the more JIRA issues there are. 

Is there only one issue per grant? If so, you could save the link on creation.

**Comment by rsmith013** [comment]
links to JIRA are a database field so no lookup in JIRA
