### ISSUE TITLE
merged grants from old datamad need to be ordered by something

### ISSUE THREAD

**Issue by ellesmith88** [cedadev/datamad2#78]
maybe date added needs to be overridden?

**Comment by ellesmith88** [comment]
could use actual start date for initial ordering of table

**Comment by rsmith013** [comment]
We should use the date from the initial data dump rather than create one

**Comment by ellesmith88** [comment]
The proposed start date has been used. This happens when the csv is merged so leaves any grants that aren't in the csv with the date of the data dump. This is quite a few grants and puts them in an odd place in the list. 

This also gives a small number of grants a 'date added' that is in the future - also a bit strange.

Needs a bit more thought/work.

**Comment by rsmith013** [comment]
yes. This will be a problem which goes away once the regular data dumps are uploaded.

**Comment by rsmith013** [comment]
ordering can be selected and are using the dates from sharepoint datamad. This is in production now.
