### ISSUE TITLE
Claim/unclaim button in grant detail does not work if you try to toggle it in the same view

### ISSUE THREAD

**Issue by rsmith013** [cedadev/datamad2#88]
I believe it is because the javascript event listeners are only set up on page load.
Because the class changes when you click the button, there is no longer an event listener attached.

Make the class of the button the same and just change the button text. Then you can decide which URL to call based on the either the button text or a data attribute.

**Comment by ellesmith88** [comment]
this is also issue #21

**Comment by rsmith013** [comment]
Ahh, OK. I think it shouldn't be too difficult a fix.
